baseURL: http://example.org/
languageCode: en-us
title: anon-log
theme: ["PaperMod"]

# dark mode maximalism
defaultTheme: dark
disableThemeToggle: true


params:
  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    subtitle: "This is subtitle"
    buttons:
      - name: Archive
        url: "/archive"
      - name: Github
        url: "https://github.com/"
